before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
release:
  github:
    owner: simply-app
    name: env-injector
